import type { DemoScenario } from '../types';

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'normal',
    name: 'Normal Condition',
    description: 'All vitals within healthy range. Patient is resting comfortably.',
    icon: '✅',
    expectedRisk: 'LOW',
    data: {
      heartRate: 72,
      spo2: 98,
      temperature: 36.6,
      activity: 'RESTING',
      fallDetected: false,
      latitude: 18.5204,
      longitude: 73.8567,
      sos: false,
    },
  },
  {
    id: 'high_heart_rate',
    name: 'High Heart Rate',
    description: 'Elevated heart rate (130 BPM) while patient is resting — potential cardiac event.',
    icon: '❤️',
    expectedRisk: 'HIGH',
    data: {
      heartRate: 130,
      spo2: 96,
      temperature: 37.2,
      activity: 'RESTING',
      fallDetected: false,
      latitude: 18.5204,
      longitude: 73.8567,
      sos: false,
    },
  },
  {
    id: 'low_spo2',
    name: 'Low SpO₂',
    description: 'Blood oxygen level dropped to 88% — indicating possible hypoxia or respiratory distress.',
    icon: '🫁',
    expectedRisk: 'CRITICAL',
    data: {
      heartRate: 95,
      spo2: 88,
      temperature: 36.8,
      activity: 'RESTING',
      fallDetected: false,
      latitude: 18.5204,
      longitude: 73.8567,
      sos: false,
    },
  },
  {
    id: 'high_temperature',
    name: 'High Temperature',
    description: 'Body temperature at 39.2°C — fever detected. Possible infection or heat stroke.',
    icon: '🌡️',
    expectedRisk: 'HIGH',
    data: {
      heartRate: 102,
      spo2: 96,
      temperature: 39.2,
      activity: 'RESTING',
      fallDetected: false,
      latitude: 18.5204,
      longitude: 73.8567,
      sos: false,
    },
  },
  {
    id: 'fall_detected',
    name: 'Fall Detected',
    description: 'MPU6050 detected a sudden fall event. Patient may be injured and unable to respond.',
    icon: '⚠️',
    expectedRisk: 'HIGH',
    data: {
      heartRate: 110,
      spo2: 95,
      temperature: 36.9,
      activity: 'STATIONARY',
      fallDetected: true,
      latitude: 18.5204,
      longitude: 73.8567,
      sos: false,
    },
  },
  {
    id: 'critical_emergency',
    name: 'Critical Emergency',
    description: 'Multiple sensors in critical range simultaneously — immediate medical intervention required.',
    icon: '🚨',
    expectedRisk: 'CRITICAL',
    data: {
      heartRate: 145,
      spo2: 87,
      temperature: 39.8,
      activity: 'STATIONARY',
      fallDetected: true,
      latitude: 18.5204,
      longitude: 73.8567,
      sos: false,
    },
  },
  {
    id: 'sos',
    name: 'SOS Activated',
    description: 'Patient pressed the physical SOS button — manual emergency request.',
    icon: '🆘',
    expectedRisk: 'CRITICAL',
    data: {
      heartRate: 88,
      spo2: 95,
      temperature: 36.7,
      activity: 'STATIONARY',
      fallDetected: false,
      latitude: 18.5204,
      longitude: 73.8567,
      sos: true,
    },
  },
];
